### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by cyrilledelabre** [MarcSkovMadsen/awesome-streamlit#12]
Hi, great repo ! 

Just a small mistake in the Readme.md, 

On Linux, OsX or in a Windows Git Bash terminal it's
```bash
source .venv/bin/activate
```

(instead of Scripts)

Have a great day,

**Comment by MarcSkovMadsen** [comment]
Hi @cyrilledelabre . Thanks so much for reaching out.

Hmm. I actually have to write 

![image](https://user-images.githubusercontent.com/42288570/67418924-048d1880-f5cc-11e9-8ed7-05873d4b0ec4.png)

But I will add a comment that some users need to use the ...bin.. folder.

Thanks

Marc
