### ISSUE TITLE
Installation instruction for anaconda(readme.md)

### ISSUE THREAD

**Issue by dstar55** [MarcSkovMadsen/awesome-streamlit#16]
Extend Readme.md with description how to install awesome-streamlit via anaconda.
Commands would be:

Prerequisite:
- Anaconda installed

commands:
...
### create awesome-streamlit envronment
> conda create -n awesome-streamlit python=3.7.4 anaconda

### activate environment
> activate awesome-streamlit
...

**Comment by MarcSkovMadsen** [comment]
Solved
