### ISSUE TITLE
Parallel query computation question

### ISSUE THREAD

**Issue by 99snowleopards** [MarcSkovMadsen/awesome-streamlit#20]
thanks for releasing this awesome repo - it's very helpful!

I'd greatly appreciate some clarification on a basic Streamlit concept: I have a Streamlit app running on my laptop. I'd like to share the url with some friends, and would like the computation of any query based on the user inputs from each instance of the app to run in parallel, so any user would have to wait the same amount of time as a single user of the app.

Does Streamlit already handle this (via Tornado), or do I have to build in concurrent computation in my code?

I'm posting this query here as you have made an app available to multiple users that are able to use the app.

I hope my question makes sense. Looking forward to your reply.

**Comment by MarcSkovMadsen** [comment]
Hi @99snowleopards 

Thanks for asking. 

The short answer is that Streamlit/ Tornado already handles this.

Each time a user navigates to a streamlit app in his browser and independent *session* is opened and Streamlit/ Tornado handles each session in parallel.

Marc
