### ISSUE TITLE
Stream: page names with spaces crash app.

### ISSUE THREAD

**Issue by R-fred** [MarcSkovMadsen/awesome-streamlit#31]
When using page names with spaces, the application can not start. Example of the error message below.

`File "C:\Users\fches\Documents\_Programming\02_Python\tests\streamlit\LuXRD\app.py", line 7
  import src.pages.Processed samples as Processed samples
                                   ^
SyntaxError: invalid syntax`

Fix being worked on.

**Comment by MarcSkovMadsen** [comment]
Hi @R-fred 

As far as i can see the problem is that you are using spaces in the name of your python file. That is not allowed in Python.

**Comment by R-fred** [comment]
That's what I also found out and am looking into how to best correct it.
