### ISSUE TITLE
Did you find  a way to execute Script immediately?

### ISSUE THREAD

**Issue by arrabi** [MarcSkovMadsen/awesome-streamlit#33]
Hello Marc,

I read your very nice hack to create a login widget (gallery/custom_widget_hack/custom_login_widget.py)

I need a way to "unfocus" all the buttonson the form. (in javascript document.activeElement.blur())
any idea if I can use the bokeh_chart hack to run this javascript line?

I tried and I can't find a way.

**Comment by MarcSkovMadsen** [comment]
Hi @arrabi 

I've seen some people insert a tag with an error and then the script in the onerror attribute. Some like

`<a onerror="MY CODE GOES HERE"></a>` where the error is that no href is provided to the tag.

Hope something like that will work for you.
