### ISSUE TITLE
Display pyLDAvis

### ISSUE THREAD

**Issue by russell-phe** [MarcSkovMadsen/awesome-streamlit#35]
A question regarding the bokeh.models.Div workaround for running custom HTML and JS. 
I am trying to display a pyLDAvis output, and I am aware the streamlit does not support this currently. I have been attempting to use the workaround in the Custom Widgets Hack, but it does not seem to work by passing in the JS and HTML outputs from the pyLDAvis.save_html() output. Do you know of any workaround that could get the display running? I have attached a sample output from pyLDAvis.save_html(). 

Any guidance is greatly appreciated. 
[lda_vis.zip](https://github.com/MarcSkovMadsen/awesome-streamlit/files/4297492/lda_vis.zip)

**Comment by MarcSkovMadsen** [comment]
Hi  @russell-phe 

I took a look unfortunately I think this is not currently possible as you would need to import some javascript libraries to get this working. I know it is on the roadmap for Streamlit.

If you need this now you could take a look at [Panel](https://panel.holoviz.org/). It can do it.

Stay safe

Marc

**Comment by Gotticketsto360tour** [comment]
I had this issue for what seemed like an eternity. A workaround that works for me looks like this:

```
html_string = pyLDAvis.prepared_data_to_html(prepared_pyLDAvis_data)
from streamlit import components
components.v1.html(diplo_string, width=1300, height=800, scrolling=True)
```

Hope this helps someone! :)
