### ISSUE TITLE
Contribute 'python formatter' app to the gallery

### ISSUE THREAD

**Issue by stabacco** [MarcSkovMadsen/awesome-streamlit#43]
Hello There, 
I wrote a simple python code formatter app in Streamlit over the weekend and I'd be happy to contribute it to the gallery, if it's of any interest to anyone else:

Website: https://streamlit-python-formatter.herokuapp.com/
Repo: https://github.com/stabacco/streamlit-python-formatter

If you find this useful I'd be happy to submit a PR.

**Comment by MarcSkovMadsen** [comment]
Yes please. I’ve noted a few observations.

On mobile the UX is not great as the sidebar is closed and the user does not know he/ she can select things there. the app appears very empty/ simple.

On mobile it would be tedious to write some code but a user might still want to play with the settings. Maybe an add “random” code button or some initial code could solve that?
