### ISSUE TITLE
https://awesome-streamlit.org not accessible by others (404)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [MarcSkovMadsen/awesome-streamlit#5]
On my laptop I can access it

![image](https://user-images.githubusercontent.com/42288570/66623185-d6323500-ebea-11e9-8d55-8905663c4ac5.png)

On my youngest and oldest sons pc's I cannot access the site

![image](https://user-images.githubusercontent.com/42288570/66623228-f9f57b00-ebea-11e9-86a5-d77149f7986b.png)

**Comment by MarcSkovMadsen** [comment]
These are my DNS settning

![image](https://user-images.githubusercontent.com/42288570/66623303-50fb5000-ebeb-11e9-8e16-0ff1481c6d6c.png)

**Comment by MarcSkovMadsen** [comment]
These are the basics on Azure where it's hosted

![image](https://user-images.githubusercontent.com/42288570/66623357-8bfd8380-ebeb-11e9-95e3-f7d4d68a92b1.png)

![image](https://user-images.githubusercontent.com/42288570/66623373-a0da1700-ebeb-11e9-90b5-775f09352e21.png)

![image](https://user-images.githubusercontent.com/42288570/66623407-d1ba4c00-ebeb-11e9-8a36-a701cca2e5e2.png)

**Comment by MarcSkovMadsen** [comment]
It's accessible now according to https://discuss.streamlit.io/t/awesome-streamlit-org-404-message/381/3

**Comment by george66s** [comment]
Hi Marc,

The 404 error message is coming back again. I had accessed the website well a few months ago. But no longer now. Now sure what happened to the website or the Azure server. It says your website is not secure. Maybe your https certificate is expired.

Thanks
George

**Comment by MarcSkovMadsen** [comment]
Thx. I'm not running awesome-streamlit.org any more. There are so many other resources there days.
