### ISSUE TITLE
really slow/non working website

### ISSUE THREAD

**Issue by sanzoghenzo** [MarcSkovMadsen/awesome-streamlit#82]
Hi!

I just fount out about streamlit and this project, and I'm evaluating using it for my next project.

Before diving in, I was browsing projects made with streamlit, starring from awesome-streamlit.org.

Sadly, I encounter many problems in doing that:

- The first time I opened the link, nothing showed (and no loading sign) - but that could be a temporary problem in my network
- Then, I could enter the website, but it took a very long time to pass the "Please wait..." message;
- After that, the site responded for some clicks, but gave up when I tried to filter the list;
- Refreshing the page a few times brought me back to the "please wait..." message, but nothing else came up; in the chrome devtools I saw the error message of the websocket connection closed before the connection is established.

Not a great advertisement of the product, I must say!

~Is this a problem with streamlit or is it that the hosting is crippled and doesn't handle the traffic well?~
EDIT: Just tried cloning the repo and running locally, it works fine! so it's something related to the network (not on my side, I tried with both ADSL and  LTE connections, same result) or hosting

**Comment by MarcSkovMadsen** [comment]
Thanks for reporting. I will try to restart the server when I get back from holiday.

I've turned my attention to Panel and run awesome-panel.org. It's been like that for the last 2 years. I keep this site running as it's been helping a lot of users over the years.

https://medium.com/@marcskovmadsen/i-prefer-to-use-panel-for-my-data-apps-here-is-why-1ff5d2b98e8f

**Comment by sanzoghenzo** [comment]
Thanks @MarcSkovMadsen for the tip!

I just discovered streamlit from a [this Speckle tutorial](https://speckle.systems/tutorials/create-your-first-speckle-app-using-only-python/), and I didn't know about Panel... but from your post it seems the way to go (I was sold after the performance comparison on user input changes, still have to read the entire article)!

**Comment by MarcSkovMadsen** [comment]
I've restarted awesome-streamlit.org which at least solved the issue immediately after.
